// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_clockScreen
void ui_clockScreen_screen_init(void);
lv_obj_t * ui_clockScreen;
lv_obj_t * ui_secContainer;
lv_obj_t * ui_firstDigitSec;
lv_obj_t * ui_secondDigitSec;
lv_obj_t * ui_dateTime;
lv_obj_t * ui_dayEngLabel;
lv_obj_t * ui_dateLabel;
lv_obj_t * ui_yearLabel;
lv_obj_t * ui_clockDigital;
lv_obj_t * ui_topRowClock;
lv_obj_t * ui_hour1st;
lv_obj_t * ui_firstDigitHour;
lv_obj_t * ui_hour2nd;
lv_obj_t * ui_secondDigitHour;
lv_obj_t * ui_topRowClock1;
lv_obj_t * ui_min1st;
lv_obj_t * ui_firstDigitMin;
lv_obj_t * ui_min2nd;
lv_obj_t * ui_secondDigitMin;


// SCREEN: ui_menuScreen
void ui_menuScreen_screen_init(void);
lv_obj_t * ui_menuScreen;
lv_obj_t * ui_menuRoller;


// SCREEN: ui_spotifyScreen
void ui_spotifyScreen_screen_init(void);
lv_obj_t * ui_spotifyScreen;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_spotifySongImg;
lv_obj_t * ui_songName;
lv_obj_t * ui_artistName;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_currentPlaybackTime;
lv_obj_t * ui_trackLengthTime;


// SCREEN: ui_calendarScreen
void ui_calendarScreen_screen_init(void);
lv_obj_t * ui_calendarScreen;
lv_obj_t * ui_Calendar1;


// SCREEN: ui_aboutScreen
void ui_aboutScreen_screen_init(void);
lv_obj_t * ui_aboutScreen;
lv_obj_t * ui_Label4;
lv_obj_t * ui_label12;
lv_obj_t * ui_label1;
lv_obj_t * ui_label2;
lv_obj_t * ui_label3;


// SCREEN: ui_blynkScreen
void ui_blynkScreen_screen_init(void);
lv_obj_t * ui_blynkScreen;
lv_obj_t * ui_Roller1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_clockScreen_screen_init();
    ui_menuScreen_screen_init();
    ui_spotifyScreen_screen_init();
    ui_calendarScreen_screen_init();
    ui_aboutScreen_screen_init();
    ui_blynkScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_clockScreen);
}
