// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#ifndef _WATCHBETA_UI_H
#define _WATCHBETA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_clockScreen
void ui_clockScreen_screen_init(void);
extern lv_obj_t * ui_clockScreen;
extern lv_obj_t * ui_secContainer;
extern lv_obj_t * ui_firstDigitSec;
extern lv_obj_t * ui_secondDigitSec;
extern lv_obj_t * ui_dateTime;
extern lv_obj_t * ui_dayEngLabel;
extern lv_obj_t * ui_dateLabel;
extern lv_obj_t * ui_yearLabel;
extern lv_obj_t * ui_clockDigital;
extern lv_obj_t * ui_topRowClock;
extern lv_obj_t * ui_hour1st;
extern lv_obj_t * ui_firstDigitHour;
extern lv_obj_t * ui_hour2nd;
extern lv_obj_t * ui_secondDigitHour;
extern lv_obj_t * ui_topRowClock1;
extern lv_obj_t * ui_min1st;
extern lv_obj_t * ui_firstDigitMin;
extern lv_obj_t * ui_min2nd;
extern lv_obj_t * ui_secondDigitMin;
// SCREEN: ui_menuScreen
void ui_menuScreen_screen_init(void);
extern lv_obj_t * ui_menuScreen;
extern lv_obj_t * ui_menuRoller;
// SCREEN: ui_spotifyScreen
void ui_spotifyScreen_screen_init(void);
extern lv_obj_t * ui_spotifyScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_spotifySongImg;
extern lv_obj_t * ui_songName;
extern lv_obj_t * ui_artistName;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_currentPlaybackTime;
extern lv_obj_t * ui_trackLengthTime;
// SCREEN: ui_calendarScreen
void ui_calendarScreen_screen_init(void);
extern lv_obj_t * ui_calendarScreen;
extern lv_obj_t * ui_Calendar1;
// SCREEN: ui_aboutScreen
void ui_aboutScreen_screen_init(void);
extern lv_obj_t * ui_aboutScreen;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_label12;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_label3;
// SCREEN: ui_blynkScreen
void ui_blynkScreen_screen_init(void);
extern lv_obj_t * ui_blynkScreen;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);



LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_minMedium);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
