// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"

void ui_blynkScreen_screen_init(void)
{
    ui_blynkScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_blynkScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_blynkScreen);
    lv_roller_set_options(ui_Roller1, "Blynk 0\nBlynk 1\nBlynk 2\nBlynk 3\nBlynk 4", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);


}
