// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"

void ui_clockScreen_screen_init(void)
{
    ui_clockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_secContainer = lv_obj_create(ui_clockScreen);
    lv_obj_remove_style_all(ui_secContainer);
    lv_obj_set_width(ui_secContainer, 76);
    lv_obj_set_height(ui_secContainer, 51);
    lv_obj_set_x(ui_secContainer, 74);
    lv_obj_set_y(ui_secContainer, 11);
    lv_obj_set_align(ui_secContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_secContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_secContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_secContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firstDigitSec = lv_label_create(ui_secContainer);
    lv_obj_set_width(ui_firstDigitSec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firstDigitSec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firstDigitSec, 10);
    lv_obj_set_y(ui_firstDigitSec, 45);
    lv_obj_set_align(ui_firstDigitSec, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_firstDigitSec, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_firstDigitSec, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_firstDigitSec, "0");
    lv_obj_set_style_text_font(ui_firstDigitSec, &ui_font_minMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondDigitSec = lv_label_create(ui_secContainer);
    lv_obj_set_width(ui_secondDigitSec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondDigitSec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondDigitSec, 10);
    lv_obj_set_y(ui_secondDigitSec, 45);
    lv_obj_set_align(ui_secondDigitSec, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_secondDigitSec, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_secondDigitSec, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_secondDigitSec, "0");
    lv_obj_set_style_text_font(ui_secondDigitSec, &ui_font_minMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateTime = lv_obj_create(ui_clockScreen);
    lv_obj_remove_style_all(ui_dateTime);
    lv_obj_set_width(ui_dateTime, 101);
    lv_obj_set_height(ui_dateTime, 72);
    lv_obj_set_x(ui_dateTime, 91);
    lv_obj_set_y(ui_dateTime, -55);
    lv_obj_set_align(ui_dateTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dateTime, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_dateTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_dateTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dayEngLabel = lv_label_create(ui_dateTime);
    lv_obj_set_width(ui_dayEngLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayEngLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayEngLabel, -19);
    lv_obj_set_y(ui_dayEngLabel, -21);
    lv_obj_set_align(ui_dayEngLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dayEngLabel, "MON");
    lv_obj_set_style_text_font(ui_dayEngLabel, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel = lv_label_create(ui_dateTime);
    lv_obj_set_width(ui_dateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLabel, -12);
    lv_obj_set_y(ui_dateLabel, -2);
    lv_obj_set_align(ui_dateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLabel, "12 FEB");
    lv_obj_set_style_text_font(ui_dateLabel, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearLabel = lv_label_create(ui_dateTime);
    lv_obj_set_width(ui_yearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearLabel, -19);
    lv_obj_set_y(ui_yearLabel, 16);
    lv_obj_set_align(ui_yearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearLabel, "2024");
    lv_obj_set_style_text_font(ui_yearLabel, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockDigital = lv_obj_create(ui_clockScreen);
    lv_obj_remove_style_all(ui_clockDigital);
    lv_obj_set_width(ui_clockDigital, 144);
    lv_obj_set_height(ui_clockDigital, 195);
    lv_obj_set_x(ui_clockDigital, -40);
    lv_obj_set_y(ui_clockDigital, 6);
    lv_obj_set_align(ui_clockDigital, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_clockDigital, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_clockDigital, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockDigital, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topRowClock = lv_obj_create(ui_clockDigital);
    lv_obj_remove_style_all(ui_topRowClock);
    lv_obj_set_width(ui_topRowClock, 144);
    lv_obj_set_height(ui_topRowClock, 93);
    lv_obj_set_x(ui_topRowClock, -41);
    lv_obj_set_y(ui_topRowClock, -47);
    lv_obj_set_align(ui_topRowClock, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topRowClock, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topRowClock, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_topRowClock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour1st = lv_obj_create(ui_topRowClock);
    lv_obj_remove_style_all(ui_hour1st);
    lv_obj_set_width(ui_hour1st, 71);
    lv_obj_set_height(ui_hour1st, 112);
    lv_obj_set_x(ui_hour1st, -30);
    lv_obj_set_y(ui_hour1st, 2);
    lv_obj_set_align(ui_hour1st, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hour1st, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hour1st, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hour1st, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firstDigitHour = lv_label_create(ui_hour1st);
    lv_obj_set_width(ui_firstDigitHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firstDigitHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_firstDigitHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firstDigitHour, "0");
    lv_obj_set_style_text_font(ui_firstDigitHour, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour2nd = lv_obj_create(ui_topRowClock);
    lv_obj_remove_style_all(ui_hour2nd);
    lv_obj_set_width(ui_hour2nd, 71);
    lv_obj_set_height(ui_hour2nd, 102);
    lv_obj_set_x(ui_hour2nd, 35);
    lv_obj_set_y(ui_hour2nd, 2);
    lv_obj_set_align(ui_hour2nd, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hour2nd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hour2nd, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hour2nd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_secondDigitHour = lv_label_create(ui_hour2nd);
    lv_obj_set_width(ui_secondDigitHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondDigitHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_secondDigitHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondDigitHour, "0");
    lv_obj_set_style_text_font(ui_secondDigitHour, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topRowClock1 = lv_obj_create(ui_clockDigital);
    lv_obj_remove_style_all(ui_topRowClock1);
    lv_obj_set_width(ui_topRowClock1, 144);
    lv_obj_set_height(ui_topRowClock1, 93);
    lv_obj_set_x(ui_topRowClock1, 157);
    lv_obj_set_y(ui_topRowClock1, 62);
    lv_obj_set_align(ui_topRowClock1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_topRowClock1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topRowClock1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_topRowClock1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_min1st = lv_obj_create(ui_topRowClock1);
    lv_obj_remove_style_all(ui_min1st);
    lv_obj_set_width(ui_min1st, 71);
    lv_obj_set_height(ui_min1st, 102);
    lv_obj_set_x(ui_min1st, -30);
    lv_obj_set_y(ui_min1st, 2);
    lv_obj_set_align(ui_min1st, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_min1st, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_min1st, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_min1st, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firstDigitMin = lv_label_create(ui_min1st);
    lv_obj_set_width(ui_firstDigitMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firstDigitMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_firstDigitMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firstDigitMin, "0");
    lv_obj_set_style_text_font(ui_firstDigitMin, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min2nd = lv_obj_create(ui_topRowClock1);
    lv_obj_remove_style_all(ui_min2nd);
    lv_obj_set_width(ui_min2nd, 71);
    lv_obj_set_height(ui_min2nd, 102);
    lv_obj_set_x(ui_min2nd, 35);
    lv_obj_set_y(ui_min2nd, 2);
    lv_obj_set_align(ui_min2nd, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_min2nd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_min2nd, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_min2nd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_secondDigitMin = lv_label_create(ui_min2nd);
    lv_obj_set_width(ui_secondDigitMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondDigitMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_secondDigitMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondDigitMin, "0");
    lv_obj_set_style_text_font(ui_secondDigitMin, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

}
