// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"


// COMPONENT clockScreenMain

lv_obj_t * ui_clockScreenMain_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_clockScreenMain;
    cui_clockScreenMain = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_clockScreenMain);
    lv_obj_set_width(cui_clockScreenMain, 144);
    lv_obj_set_height(cui_clockScreenMain, 175);
    lv_obj_set_x(cui_clockScreenMain, -73);
    lv_obj_set_y(cui_clockScreenMain, -4);
    lv_obj_set_align(cui_clockScreenMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_clockScreenMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_clockScreenMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_clockScreenMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_hourLabel;
    cui_hourLabel = lv_label_create(cui_clockScreenMain);
    lv_obj_set_width(cui_hourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_hourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_hourLabel, -45);
    lv_obj_set_y(cui_hourLabel, -36);
    lv_obj_set_align(cui_hourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_hourLabel, "00");
    lv_obj_set_style_text_font(cui_hourLabel, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_minLabel;
    cui_minLabel = lv_label_create(cui_clockScreenMain);
    lv_obj_set_width(cui_minLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_minLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_minLabel, -45);
    lv_obj_set_y(cui_minLabel, 56);
    lv_obj_set_align(cui_minLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_minLabel, "00");
    lv_obj_set_style_text_font(cui_minLabel, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CLOCKSCREENMAIN_NUM);
    children[UI_COMP_CLOCKSCREENMAIN_CLOCKSCREENMAIN] = cui_clockScreenMain;
    children[UI_COMP_CLOCKSCREENMAIN_HOURLABEL] = cui_hourLabel;
    children[UI_COMP_CLOCKSCREENMAIN_MINLABEL] = cui_minLabel;
    lv_obj_add_event_cb(cui_clockScreenMain, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_clockScreenMain, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_clockScreenMain_create_hook(cui_clockScreenMain);
    return cui_clockScreenMain;
}

