// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"

void ui_calendarScreen_screen_init(void)
{
    ui_calendarScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_calendarScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_calendarScreen);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 240);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_Calendar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Calendar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Calendar1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);


}
