// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#ifndef _UI_COMP_CLOCKSCREENMAIN_H
#define _UI_COMP_CLOCKSCREENMAIN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT clockScreenMain
#define UI_COMP_CLOCKSCREENMAIN_CLOCKSCREENMAIN 0
#define UI_COMP_CLOCKSCREENMAIN_HOURLABEL 1
#define UI_COMP_CLOCKSCREENMAIN_MINLABEL 2
#define _UI_COMP_CLOCKSCREENMAIN_NUM 3
lv_obj_t * ui_clockScreenMain_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
