// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"

void ui_menuScreen_screen_init(void)
{
    ui_menuScreen = lv_obj_create(NULL);

    ui_menuRoller = lv_roller_create(ui_menuScreen);
    lv_roller_set_options(ui_menuRoller, "Clock\nSpotify\nBlynk Control\nCalendar\nAbout\nExit", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_menuRoller, 200);
    lv_obj_set_width(ui_menuRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_menuRoller, LV_ALIGN_CENTER);


}
