// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: watchBeta

#include "ui.h"

void ui_spotifyScreen_screen_init(void)
{
    ui_spotifyScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_spotifyScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_spotifyScreen);
    lv_obj_set_width(ui_Panel1, 269);
    lv_obj_set_height(ui_Panel1, 259);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x1DB954), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spotifySongImg = lv_img_create(ui_spotifyScreen);
    lv_img_set_src(ui_spotifySongImg, &ui__temporary_image);
    lv_obj_set_width(ui_spotifySongImg, 140);
    lv_obj_set_height(ui_spotifySongImg, 140);
    lv_obj_set_x(ui_spotifySongImg, 0);
    lv_obj_set_y(ui_spotifySongImg, -35);
    lv_obj_set_align(ui_spotifySongImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_spotifySongImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_spotifySongImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_songName = lv_label_create(ui_spotifyScreen);
    lv_obj_set_width(ui_songName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_songName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_songName, 0);
    lv_obj_set_y(ui_songName, 49);
    lv_obj_set_align(ui_songName, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_songName, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_songName, "TITLE TITLE TITLE TITLE TITLE TITLE TITLE");
    lv_obj_set_style_text_font(ui_songName, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistName = lv_label_create(ui_spotifyScreen);
    lv_obj_set_width(ui_artistName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_artistName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_artistName, 0);
    lv_obj_set_y(ui_artistName, 64);
    lv_obj_set_align(ui_artistName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_artistName, "ARTIST ARTIST");
    lv_obj_set_style_text_font(ui_artistName, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_spotifyScreen);
    lv_bar_set_value(ui_Bar1, 8, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 250);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 115);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Bar1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Bar1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_currentPlaybackTime = lv_label_create(ui_spotifyScreen);
    lv_obj_set_width(ui_currentPlaybackTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentPlaybackTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentPlaybackTime, -96);
    lv_obj_set_y(ui_currentPlaybackTime, 96);
    lv_obj_set_align(ui_currentPlaybackTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentPlaybackTime, "12:12");
    lv_obj_set_style_text_font(ui_currentPlaybackTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_trackLengthTime = lv_label_create(ui_spotifyScreen);
    lv_obj_set_width(ui_trackLengthTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_trackLengthTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_trackLengthTime, 96);
    lv_obj_set_y(ui_trackLengthTime, 96);
    lv_obj_set_align(ui_trackLengthTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_trackLengthTime, "12:12");
    lv_obj_set_style_text_font(ui_trackLengthTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
